AWSTemplateFormatVersion: 2010-09-09
Description: Scim Route53 resources for the account
Parameters:
  Service:
    Description: The service or product this stack supports
    Type: String
    AllowedValues:
      - vc
  Owner:
    Description: The key contact / stack holder of this stack
    Type: String
    Default: jonathan.dodd@reckonsoftware.com
Resources:
  pocLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: poc-lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
                - logs.amazonaws.com
                - lambda.amazonaws.com
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: poc-lambda-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                - logs:*
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetBucketVersioning
                - s3:ListBucket
                - s3:DeleteObject
                - apigateway:*
                - iam:*
                - cloudformation:*
                - codedeploy:*
                Resource: "*"
  # pocLambdaSAM:
  #   Type: 'AWS::Serverless::Function'
  #   Properties:
  #     CodeUri:  s3://poc-lambda/poc.zip
  #     FunctionName: poc-lambda-function
  #     Handler: index.handler
  #     MemorySize: 128
  #     Role:
  #       Fn::GetAtt: pocLambdaRole.Arn
  #     Runtime: nodejs8.10
  #     Timeout: 60      
  pocLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: poc-lambda
        S3Key:  poc.zip
      Description: POC function used to test automated deployments of lambda functions
      FunctionName: poc-lambda-function
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt: pocLambdaRole.Arn
      Runtime: nodejs8.10
      Timeout: 60